name = "skipi-landing"
main = "src/worker.js"
compatibility_date = "2024-09-23"
account_id = "6b9b3fa0e9f6be87faf7ca1b212641a3"

[placement]
mode = "smart"

[observability.logs]
enabled = false
invocation_logs = true

[assets]
directory = "./public"
